apiVersion: v1
kind: Pod
metadata:
  name: emptydir
  labels:
    project: roboshop

spec:
  containers: 
  - name: nginx
    image: nginx
    volumeMounts:
    - mountPath: /var/log/
      name: emptydemo-vol
      
  - name: almalinux
    image: almalinux:9
    command: ["sleep", "10000" ]
    volumeMounts:
    - mountPath: /mnt/nginx
      name: emptydemo-vol
      readOnly: true

  volumes:
  - name: emptydemo-vol
    emptyDir:
      sizeLimit: 100Mi