apiVersion: v1
kind: pod
metadata:
  name: nginx
  description: nginx pod
  labels:
    name: nginx
    type: learn

spec:
  containers: 
  - name: nginx
  - image: nginx
    ports:
  - container ports: 80
