apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: roboshop
  labels:
    name: nginx
    type: learn

spec:
  containers: 
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    - targetPort: 8080
    - port: 80