apiVersion: v1
kind: Pod
metadata:
  name: frontend
  namespace: roboshop
  labels:
    - name: frontend
      project: roboshop
      component: ui
      url: devops.command

spec:
  containers:
    - name: frontend
      image: nginx