apiVersion: v1
kind: Pod
metadata:
  name: error-test
labels:
  name: error-test
  project: devops
  url: devops.com

spec:
  containers:
  - name: nginx
    image: nginx
  - name: almalinux
    image: almalinux:9