apiVersion: v1
kind: Pod
metadata:
  name: annotations-demo
  namespace: roboshop
  annotations:
    name: annotationsdemopod
    url: https://pro.dev.com/build/jenkins/5/ko

spec:
  containers:
   - name: nginx
     image: nginx
     resources:
        requests:
          cpu: "50m"
          memory: "68mi"
        limits:
          cpu: "100m"
          memory: "136mi"
        env:
          - name: course
            value: devops
          - name: module
            value: kubernetes
          - name: trainer
            value: siva