apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    project: roboshop
    course: devk8s
    key: learn
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 80 #container port