apiVersion: v1
kind: Pod
metadata:
  name: loadbalancer
  labels:
    project: roboshop
    course: devk8s
    key: learn
    purpose: LoadBalancer

spec:
  containers:
  - name: nginx
    image: nginx
